# Generated by Django 4.2.3 on 2024-02-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yqpointrecord',
            name='source_type',
            field=models.SmallIntegerField(choices=[(0, '系统操作'), (1, '每日签到'), (2, '参与活动'), (3, '问题反馈'), (4, '达成成就'), (5, '填写问卷'), (6, '奖池花费'), (7, '奖池补偿')], default=0, verbose_name='来源类型'),
        ),
        migrations.CreateModel(
            name='PermissionBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission', verbose_name='权限')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '权限黑名单',
                'verbose_name_plural': '权限黑名单',
            },
        ),
    ]
